//for setup snd task management requirments and user stories

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Types } from 'mongoose';
import { Employee } from '../../employee.schema';

export enum TaskStatus {
  Pending = 'pending',
  InProgress = 'in_progress',
  Completed = 'completed',
}

export type OnboardingTaskDocument = HydratedDocument<OnboardingTask>;

@Schema({ timestamps: true })
export class OnboardingTask {
  @Prop({ type: Types.ObjectId, ref: Employee.name, required: true })
  employeeId: Types.ObjectId;

  @Prop({ type: String, required: true })
  taskName: string;

  @Prop({ type: String })
  taskDescription: string;

  @Prop({
    type: String,
    enum: Object.values(TaskStatus),
    required: true,
    default: TaskStatus.Pending,
  })
  status: TaskStatus;

  @Prop({ type: Date, required: true })
  dueDate: Date;

  @Prop({ type: Date })
  completedAt: Date;

  @Prop({ type: String })
  department: string;

  @Prop({ type: Boolean, default: false })
  isAutoGenerated: boolean;

  @Prop({ type: Number, default: 0 })
  orderIndex: number;
}

export const OnboardingTaskSchema = SchemaFactory.createForClass(OnboardingTask);